name = "FlipBoard"
uuid = "96c49371-6108-43a2-a244-1c47317f47be"
authors = ["hannahilea <hannahilea@users.noreply.github.com>", "aferguso2 <aferguso2@users.noreply.github.com>, and contributors"]
version = "0.0.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
