name = "FlipBoard"
uuid = "96c49371-6108-43a2-a244-1c47317f47be"
authors = ["hannahilea <hannahilea@users.noreply.github.com>", "aferguso2 <aferguso2@users.noreply.github.com>, and contributors"]
version = "0.0.4"

[deps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
Aqua = "0.6"
LibSerialPort = "0.5.2"
julia = "1.5"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
